//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isTakipProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Competent { get; set; }
        public string Telephone { get; set; }
        public string Mail { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Address { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
